tmax=525600
seed=1
grad_norm_clip=10000

REW=marlisa
export CUDA_VISIBLE_DEVICES=0 && python src/main.py --config=iql-cem --env-config=citylearn with batch_size=256 rnn_hidden_dim=256 naf_hidden_dim=256   weight_decay=False buffer_size=10000 test_interval=8759 target_update_tau=0.005 test_nepisode=1 optimizer_epsilon=0.00000001 t_max=$tmax seed=$seed start_steps=600 grad_norm_clip=$grad_norm_clip n_train=2  env_args.reward_style=$REW > logs/$seed-$REW-iql-cem.log 2>&1 &
export CUDA_VISIBLE_DEVICES=1 && python src/main.py --config=maddpg     --env-config=citylearn with batch_size=256 rnn_hidden_dim=256 naf_hidden_dim=256   weight_decay=False buffer_size=10000 test_interval=8759 target_update_tau=0.005 test_nepisode=1 optimizer_epsilon=0.00000001 t_max=$tmax seed=$seed start_steps=600 grad_norm_clip=$grad_norm_clip n_train=2 env_args.reward_style=$REW  > logs/$seed-$REW-maddpg.log     2>&1 &
export CUDA_VISIBLE_DEVICES=2 && python src/main.py --config=covdn-naf --env-config=citylearn with batch_size=256 rnn_hidden_dim=256 naf_hidden_dim=256   weight_decay=False buffer_size=10000 test_interval=8759 target_update_tau=0.005 test_nepisode=1 optimizer_epsilon=0.00000001 t_max=$tmax seed=$seed start_steps=600 grad_norm_clip=$grad_norm_clip n_train=2  env_args.reward_style=$REW > logs/$seed-$REW-covdn-naf.log 2>&1 &


REW=exp
export CUDA_VISIBLE_DEVICES=3 && python src/main.py --config=iql-cem --env-config=citylearn with batch_size=256 rnn_hidden_dim=256 naf_hidden_dim=256   weight_decay=False buffer_size=10000 test_interval=8759 target_update_tau=0.005 test_nepisode=1 optimizer_epsilon=0.00000001 t_max=$tmax seed=$seed start_steps=600 grad_norm_clip=$grad_norm_clip n_train=2  env_args.reward_style=$REW > logs/$seed-$REW-iql-cem.log 2>&1 &
export CUDA_VISIBLE_DEVICES=0 && python src/main.py --config=maddpg     --env-config=citylearn with batch_size=256 rnn_hidden_dim=256 naf_hidden_dim=256   weight_decay=False buffer_size=10000 test_interval=8759 target_update_tau=0.005 test_nepisode=1 optimizer_epsilon=0.00000001 t_max=$tmax seed=$seed start_steps=600 grad_norm_clip=$grad_norm_clip n_train=2 env_args.reward_style=$REW  > logs/$seed-$REW-maddpg.log     2>&1 &
export CUDA_VISIBLE_DEVICES=1 && python src/main.py --config=covdn-naf --env-config=citylearn with batch_size=256 rnn_hidden_dim=256 naf_hidden_dim=256   weight_decay=False buffer_size=10000 test_interval=8759 target_update_tau=0.005 test_nepisode=1 optimizer_epsilon=0.00000001 t_max=$tmax seed=$seed start_steps=600 grad_norm_clip=$grad_norm_clip n_train=2  env_args.reward_style=$REW > logs/$seed-$REW-covdn-naf.log 2>&1 &


REW=ramping_square
export CUDA_VISIBLE_DEVICES=2 && python src/main.py --config=iql-cem --env-config=citylearn with batch_size=256 rnn_hidden_dim=256 naf_hidden_dim=256   weight_decay=False buffer_size=10000 test_interval=8759 target_update_tau=0.005 test_nepisode=1 optimizer_epsilon=0.00000001 t_max=$tmax seed=$seed start_steps=600 grad_norm_clip=$grad_norm_clip n_train=2  env_args.reward_style=$REW > logs/$seed-$REW-iql-cem.log 2>&1 &
export CUDA_VISIBLE_DEVICES=3 && python src/main.py --config=maddpg     --env-config=citylearn with batch_size=256 rnn_hidden_dim=256 naf_hidden_dim=256   weight_decay=False buffer_size=10000 test_interval=8759 target_update_tau=0.005 test_nepisode=1 optimizer_epsilon=0.00000001 t_max=$tmax seed=$seed start_steps=600 grad_norm_clip=$grad_norm_clip n_train=2 env_args.reward_style=$REW  > logs/$seed-$REW-maddpg.log     2>&1 &
export CUDA_VISIBLE_DEVICES=0 && python src/main.py --config=covdn-naf --env-config=citylearn with batch_size=256 rnn_hidden_dim=256 naf_hidden_dim=256   weight_decay=False buffer_size=10000 test_interval=8759 target_update_tau=0.005 test_nepisode=1 optimizer_epsilon=0.00000001 t_max=$tmax seed=$seed start_steps=600 grad_norm_clip=$grad_norm_clip n_train=2  env_args.reward_style=$REW > logs/$seed-$REW-covdn-naf.log 2>&1 &

REW=mixed
export CUDA_VISIBLE_DEVICES=1 && python src/main.py --config=iql-cem --env-config=citylearn with batch_size=256 rnn_hidden_dim=256 naf_hidden_dim=256   weight_decay=False buffer_size=10000 test_interval=8759 target_update_tau=0.005 test_nepisode=1 optimizer_epsilon=0.00000001 t_max=$tmax seed=$seed start_steps=600 grad_norm_clip=$grad_norm_clip n_train=2  env_args.reward_style=$REW > logs/$seed-$REW-iql-cem.log 2>&1 &
export CUDA_VISIBLE_DEVICES=2 && python src/main.py --config=maddpg     --env-config=citylearn with batch_size=256 rnn_hidden_dim=256 naf_hidden_dim=256   weight_decay=False buffer_size=10000 test_interval=8759 target_update_tau=0.005 test_nepisode=1 optimizer_epsilon=0.00000001 t_max=$tmax seed=$seed start_steps=600 grad_norm_clip=$grad_norm_clip n_train=2 env_args.reward_style=$REW  > logs/$seed-$REW-maddpg.log     2>&1 &
export CUDA_VISIBLE_DEVICES=3 && python src/main.py --config=covdn-naf --env-config=citylearn with batch_size=256 rnn_hidden_dim=256 naf_hidden_dim=256   weight_decay=False buffer_size=10000 test_interval=8759 target_update_tau=0.005 test_nepisode=1 optimizer_epsilon=0.00000001 t_max=$tmax seed=$seed start_steps=600 grad_norm_clip=$grad_norm_clip n_train=2  env_args.reward_style=$REW > logs/$seed-$REW-covdn-naf.log 2>&1 &
