{
 "title": "CityLearn",
 "time": { "from": "1970-01-01T06:00:00.000Z", "to": "1973-12-31T06:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "simulation_id", "label": "Simulation ID", "query": "SELECT id FROM simulation" },
   {
    "name": "building_name",
    "label": "Building Name",
    "query": "SELECT b.name FROM building b LEFT JOIN environment e ON e.id = b.environment_id WHERE e.simulation_id = ${simulation_id}"
   },
   { "name": "basic_rbc_environment_id", "query": "38" },
   { "name": "optimized_rbc_environment_id", "query": "40" },
   { "name": "timezone_offset", "query": "6" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 22, "x": 1, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT\ns.start_timestamp AS \"Started\",\ns.end_timestamp AS  \"Ended\",\nCASE WHEN s.successful = 1 THEN 'True' ELSE 'False' END AS \"Successful\",\ne.simulation_period_start AS \"Simulation Start Timestep\",\ne.simulation_period_end AS \"Simulation End Timestep\",\nMAX(timestep) AS \"Timesteps\",\nMAX(t.episode) + 1 AS \"Episodes\",\nMIN(a.seed) AS \"Seed\",\nCASE WHEN e.central_agent = 1 THEN 'True' ELSE 'False' END AS \"Central Agent\",\nMIN(a.name) AS \"Agent\",\nMIN(a.reward_style) AS \"Reward\"\nFROM simulation s\nLEFT JOIN environment e ON e.simulation_id = s.id\nLEFT JOIN building b ON b.environment_id = e.id\nLEFT JOIN agent a ON b.agent_id = a.id\nLEFT JOIN timestep t ON t.environment_id = e.id\nWHERE s.id = ${simulation_id}",
     "rawQueryText": "SELECT\ns.start_timestamp AS \"Started\",\ns.end_timestamp AS  \"Ended\",\nCASE WHEN s.successful = 1 THEN 'True' ELSE 'False' END AS \"Successful\",\ne.simulation_period_start AS \"Simulation Start Timestep\",\ne.simulation_period_end AS \"Simulation End Timestep\",\nMAX(timestep) AS \"Timesteps\",\nMAX(t.episode) + 1 AS \"Episodes\",\nMIN(a.seed) AS \"Seed\",\nCASE WHEN e.central_agent = 1 THEN 'True' ELSE 'False' END AS \"Central Agent\",\nMIN(a.name) AS \"Agent\",\nMIN(a.reward_style) AS \"Reward\"\nFROM simulation s\nLEFT JOIN environment e ON e.simulation_id = s.id\nLEFT JOIN building b ON b.environment_id = e.id\nLEFT JOIN agent a ON b.agent_id = a.id\nLEFT JOIN timestep t ON t.environment_id = e.id\nWHERE s.id = ${simulation_id}",
     "timeColumns": [
      "start_timestamp",
      "end_timestamp"
     ]
    }
   ]
  },
  { "title": "METADATA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Building",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nCOUNT(b.id)\nFROM building b\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nCOUNT(b.id)\nFROM building b\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "PV Capacity (kW)",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 4 },
   "targets": [
    {
     "queryText": "SELECT\nb.solar_power_installed\nFROM building b\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nb.solar_power_installed\nFROM building b\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Cooling Device",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nCOUNT(d.id)\nFROM cooling_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE d.nominal_power > 0.001\nAND e.simulation_id = ${simulation_id}\n",
     "rawQueryText": "SELECT\nCOUNT(d.id)\nFROM cooling_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE d.nominal_power > 0.001\nAND e.simulation_id = ${simulation_id}\n"
    }
   ]
  },
  {
   "title": "Nominal Power (kW)",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT\nd.nominal_power AS \"Nominal Power (kW)\"\nFROM cooling_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.nominal_power AS \"Nominal Power (kW)\"\nFROM cooling_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Technical Efficiency",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT\nd.eta_tech AS \"Technical Efficiency\"\nFROM cooling_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.eta_tech AS \"Technical Efficiency\"\nFROM cooling_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Cooling Target Temp. (C",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT\nd.t_target_cooling AS \"Cooling Target Temp. (C)\"\nFROM cooling_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.t_target_cooling AS \"Cooling Target Temp. (C)\"\nFROM cooling_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Heating Target Temp. (C)",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT\nd.t_target_heating AS \"Heating Target Temp. (C)\"\nFROM cooling_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.t_target_heating AS \"Heating Target Temp. (C)\"\nFROM cooling_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "DHW Heating Device",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nCOUNT(d.id)\nFROM dhw_heating_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE d.nominal_power > 0.001\nAND e.simulation_id = ${simulation_id}\n",
     "rawQueryText": "SELECT\nCOUNT(d.id)\nFROM dhw_heating_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE d.nominal_power > 0.001\nAND e.simulation_id = ${simulation_id}\n"
    }
   ]
  },
  {
   "title": "Nominal Power (kW)",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 9, "x": 4, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT\nd.nominal_power AS \"Nominal Power (kW)\"\nFROM dhw_heating_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.nominal_power AS \"Nominal Power (kW)\"\nFROM dhw_heating_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT\nd.efficiency AS \"Efficiency\"\nFROM dhw_heating_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.efficiency AS \"Efficiency\"\nFROM dhw_heating_device d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Cooling Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nCOUNT(d.id)\nFROM cooling_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE d.capacity > 0.001\nAND e.simulation_id = ${simulation_id}\n",
     "rawQueryText": "SELECT\nCOUNT(d.id)\nFROM cooling_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE d.capacity > 0.001\nAND e.simulation_id = ${simulation_id}\n"
    }
   ]
  },
  {
   "title": "Capacity (kW)",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT\nd.capacity AS \"Capacity (kW)\"\nFROM cooling_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.capacity AS \"Capacity (kW)\"\nFROM cooling_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Max. Power Output (kW)",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT\nd.max_power_output AS \"Max. Power Output (kW)\"\nFROM cooling_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.max_power_output AS \"Max. Power Output (kW)\"\nFROM cooling_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Max. Power Charging (kW)",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT\nd.max_power_charging AS \"Max. Power Charging (kW)\"\nFROM cooling_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.max_power_charging AS \"Max. Power Charging (kW)\"\nFROM cooling_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT\nd.efficiency AS \"Efficiency\"\nFROM cooling_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.efficiency AS \"Efficiency\"\nFROM cooling_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Loss Coefficient",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT\nd.loss_coef AS \"Loss Coefficient\"\nFROM cooling_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.loss_coef AS \"Loss Coefficient\"\nFROM cooling_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "DHW Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nCOUNT(d.id)\nFROM dhw_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE d.capacity > 0.001\nAND e.simulation_id = ${simulation_id}\n",
     "rawQueryText": "SELECT\nCOUNT(d.id)\nFROM dhw_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE d.capacity > 0.001\nAND e.simulation_id = ${simulation_id}\n"
    }
   ]
  },
  {
   "title": "Capacity (kW)",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT\nd.capacity AS \"Capacity (kW)\"\nFROM dhw_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.capacity AS \"Capacity (kW)\"\nFROM dhw_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Max. Power Output (kW)",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT\nd.max_power_output AS \"Max. Power Output (kW)\"\nFROM dhw_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.max_power_output AS \"Max. Power Output (kW)\"\nFROM dhw_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Max. Power Charging (kW)",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT\nd.max_power_charging AS \"Max. Power Charging (kW)\"\nFROM dhw_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.max_power_charging AS \"Max. Power Charging (kW)\"\nFROM dhw_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT\nd.efficiency AS \"Efficiency\"\nFROM dhw_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.efficiency AS \"Efficiency\"\nFROM dhw_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Loss Coefficient",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT\nd.loss_coef AS \"Loss Coefficient\"\nFROM dhw_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.loss_coef AS \"Loss Coefficient\"\nFROM dhw_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Electrical Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\nCOUNT(d.id)\nFROM electrical_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE d.capacity > 0.001\nAND e.simulation_id = ${simulation_id}\n",
     "rawQueryText": "SELECT\nCOUNT(d.id)\nFROM electrical_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE d.capacity > 0.001\nAND e.simulation_id = ${simulation_id}\n"
    }
   ]
  },
  {
   "title": "Capacity (kW)",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT\nd.capacity AS \"Capacity (kWh)\"\nFROM electrical_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.capacity AS \"Capacity (kWh)\"\nFROM electrical_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Nominal Power (kW)",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT\nd.nominal_power\nFROM electrical_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.nominal_power\nFROM electrical_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Capacity Loss Coefficient",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT\nd.capacity_loss_coef\nFROM electrical_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.capacity_loss_coef\nFROM electrical_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT\nd.efficiency\nFROM electrical_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.efficiency\nFROM electrical_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Loss Coefficient",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT\nd.loss_coef\nFROM electrical_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\nd.loss_coef\nFROM electrical_storage d\nLEFT JOIN building b ON b.id = d.building_id\nLEFT JOIN environment e ON e.id = b.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "WEATHER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Dry-Bulb Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "queryText": "SELECT\n(t.timestep + ${timezone_offset})*3600 AS timestamp,\nw.outdoor_drybulb_temperature\nFROM weather_timeseries w\nLEFT JOIN timestep t ON t.id = w.timestep_id\nLEFT JOIN environment_timeseries s ON s.timestep_id = w.timestep_id\nLEFT JOIN environment e ON e.id = s.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\n(t.timestep + ${timezone_offset})*3600 AS timestamp,\nw.outdoor_drybulb_temperature\nFROM weather_timeseries w\nLEFT JOIN timestep t ON t.id = w.timestep_id\nLEFT JOIN environment_timeseries s ON s.timestep_id = w.timestep_id\nLEFT JOIN environment e ON e.id = s.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [ "timestamp" ]
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "queryText": "SELECT\n(t.timestep + ${timezone_offset})*3600 AS timestamp,\nw.outdoor_relative_humidity\nFROM weather_timeseries w\nLEFT JOIN timestep t ON t.id = w.timestep_id\nLEFT JOIN environment_timeseries s ON s.timestep_id = w.timestep_id\nLEFT JOIN environment e ON e.id = s.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\n(t.timestep + ${timezone_offset})*3600 AS timestamp,\nw.outdoor_relative_humidity\nFROM weather_timeseries w\nLEFT JOIN timestep t ON t.id = w.timestep_id\nLEFT JOIN environment_timeseries s ON s.timestep_id = w.timestep_id\nLEFT JOIN environment e ON e.id = s.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [ "timestamp" ]
    }
   ]
  },
  {
   "title": "Solar Irradiation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "W/m^2" }
   ],
   "targets": [
    {
     "queryText": "SELECT\n(t.timestep + ${timezone_offset})*3600 AS timestamp,\nw.diffuse_solar_radiation AS diffuse,\nw.direct_solar_radiation AS direct\nFROM weather_timeseries w\nLEFT JOIN timestep t ON t.id = w.timestep_id\nLEFT JOIN environment_timeseries s ON s.timestep_id = w.timestep_id\nLEFT JOIN environment e ON e.id = s.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\n(t.timestep + ${timezone_offset})*3600 AS timestamp,\nw.diffuse_solar_radiation AS diffuse,\nw.direct_solar_radiation AS direct\nFROM weather_timeseries w\nLEFT JOIN timestep t ON t.id = w.timestep_id\nLEFT JOIN environment_timeseries s ON s.timestep_id = w.timestep_id\nLEFT JOIN environment e ON e.id = s.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [ "timestamp" ]
    }
   ]
  },
  { "title": "ENVIRONMENT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 48 },
   "options": {
    "content": "<h5><center>Energy Flexibility KPI<center><h5>"
   }
  },
  {
   "title": "Average",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 50 },
   "targets": [
    {
     "queryText": "WITH c_union AS (\nSELECT *, 1 AS label FROM ramping_cost_function\nUNION ALL\nSELECT *, 2 AS label FROM load_factor_cost_function\nUNION ALL\nSELECT *, 3 AS label FROM average_daily_peak_cost_function\nUNION ALL\nSELECT *, 4 AS label FROM annual_peak_cost_function\nUNION ALL\nSELECT *, 5 AS label FROM net_electric_consumption_cost_function\n)\n\nSELECT\n(s.timestep + ${timezone_offset})*3600 AS timestamp,\nAVG(s.value/b.value) AS basic,\nAVG(s.value/o.value) AS optimized\nFROM c_union s\nLEFT JOIN environment e ON e.id = s.environment_id\nLEFT JOIN (\nSELECT * FROM c_union WHERE environment_id = ${basic_rbc_environment_id}\n) b ON b.timestep = s.timestep AND b.label = s.label\nLEFT JOIN (\nSELECT * FROM c_union WHERE environment_id = ${optimized_rbc_environment_id}\n) o ON o.timestep = s.timestep AND o.label = s.label\nWHERE e.simulation_id = ${simulation_id}\nGROUP BY\ns.timestep,\ns.environment_id",
     "rawQueryText": "WITH c_union AS (\nSELECT *, 1 AS label FROM ramping_cost_function\nUNION ALL\nSELECT *, 2 AS label FROM load_factor_cost_function\nUNION ALL\nSELECT *, 3 AS label FROM average_daily_peak_cost_function\nUNION ALL\nSELECT *, 4 AS label FROM annual_peak_cost_function\nUNION ALL\nSELECT *, 5 AS label FROM net_electric_consumption_cost_function\n)\n\nSELECT\n(s.timestep + ${timezone_offset})*3600 AS timestamp,\nAVG(s.value/b.value) AS basic,\nAVG(s.value/o.value) AS optimized\nFROM c_union s\nLEFT JOIN environment e ON e.id = s.environment_id\nLEFT JOIN (\nSELECT * FROM c_union WHERE environment_id = ${basic_rbc_environment_id}\n) b ON b.timestep = s.timestep AND b.label = s.label\nLEFT JOIN (\nSELECT * FROM c_union WHERE environment_id = ${optimized_rbc_environment_id}\n) o ON o.timestep = s.timestep AND o.label = s.label\nWHERE e.simulation_id = ${simulation_id}\nGROUP BY\ns.timestep,\ns.environment_id",
     "timeColumns": [ "timestamp" ]
    }
   ]
  },
  {
   "title": "Ramping",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT\n(s.timestep + ${timezone_offset})*3600 AS timestamp,\ns.value/b.value AS basic,\ns.value/o.value AS optimized\nFROM ramping_cost_function s\nLEFT JOIN environment e ON e.id = s.environment_id\nLEFT JOIN (\nSELECT timestep, value FROM   ramping_cost_function WHERE environment_id = ${basic_rbc_environment_id}\n) b ON b.timestep = s.timestep\nLEFT JOIN (\nSELECT timestep, value FROM   ramping_cost_function WHERE environment_id = ${optimized_rbc_environment_id}\n) o ON o.timestep = s.timestep\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\n(s.timestep + ${timezone_offset})*3600 AS timestamp,\ns.value/b.value AS basic,\ns.value/o.value AS optimized\nFROM ramping_cost_function s\nLEFT JOIN environment e ON e.id = s.environment_id\nLEFT JOIN (\nSELECT timestep, value FROM   ramping_cost_function WHERE environment_id = ${basic_rbc_environment_id}\n) b ON b.timestep = s.timestep\nLEFT JOIN (\nSELECT timestep, value FROM   ramping_cost_function WHERE environment_id = ${optimized_rbc_environment_id}\n) o ON o.timestep = s.timestep\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [ "timestamp" ]
    }
   ]
  },
  {
   "title": "Load Factor",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 50 },
   "targets": [
    {
     "queryText": "SELECT\n(s.timestep + ${timezone_offset})*3600 AS timestamp,\ns.value/b.value AS basic,\ns.value/o.value AS optimized\nFROM load_factor_cost_function s\nLEFT JOIN environment e ON e.id = s.environment_id\nLEFT JOIN (\nSELECT timestep, value FROM   load_factor_cost_function WHERE environment_id = ${basic_rbc_environment_id}\n) b ON b.timestep = s.timestep\nLEFT JOIN (\nSELECT timestep, value FROM   load_factor_cost_function WHERE environment_id = ${optimized_rbc_environment_id}\n) o ON o.timestep = s.timestep\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\n(s.timestep + ${timezone_offset})*3600 AS timestamp,\ns.value/b.value AS basic,\ns.value/o.value AS optimized\nFROM load_factor_cost_function s\nLEFT JOIN environment e ON e.id = s.environment_id\nLEFT JOIN (\nSELECT timestep, value FROM   load_factor_cost_function WHERE environment_id = ${basic_rbc_environment_id}\n) b ON b.timestep = s.timestep\nLEFT JOIN (\nSELECT timestep, value FROM   load_factor_cost_function WHERE environment_id = ${optimized_rbc_environment_id}\n) o ON o.timestep = s.timestep\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [ "timestamp" ]
    }
   ]
  },
  {
   "title": "Average Daily Peak",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 50 },
   "targets": [
    {
     "queryText": "SELECT\n(s.timestep + ${timezone_offset})*3600 AS timestamp,\ns.value/b.value AS basic,\ns.value/o.value AS optimized\nFROM average_daily_peak_cost_function s\nLEFT JOIN environment e ON e.id = s.environment_id\nLEFT JOIN (\nSELECT timestep, value FROM  average_daily_peak_cost_function WHERE environment_id = ${basic_rbc_environment_id}\n) b ON b.timestep = s.timestep\nLEFT JOIN (\nSELECT timestep, value FROM  average_daily_peak_cost_function WHERE environment_id = ${optimized_rbc_environment_id}\n) o ON o.timestep = s.timestep\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\n(s.timestep + ${timezone_offset})*3600 AS timestamp,\ns.value/b.value AS basic,\ns.value/o.value AS optimized\nFROM average_daily_peak_cost_function s\nLEFT JOIN environment e ON e.id = s.environment_id\nLEFT JOIN (\nSELECT timestep, value FROM  average_daily_peak_cost_function WHERE environment_id = ${basic_rbc_environment_id}\n) b ON b.timestep = s.timestep\nLEFT JOIN (\nSELECT timestep, value FROM  average_daily_peak_cost_function WHERE environment_id = ${optimized_rbc_environment_id}\n) o ON o.timestep = s.timestep\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [ "timestamp" ]
    }
   ]
  },
  {
   "title": "Annual Peak",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 50 },
   "targets": [
    {
     "queryText": "SELECT\n(s.timestep + ${timezone_offset})*3600 AS timestamp,\ns.value/b.value AS basic,\ns.value/o.value AS optimized\nFROM annual_peak_cost_function s\nLEFT JOIN environment e ON e.id = s.environment_id\nLEFT JOIN (\nSELECT timestep, value FROM  annual_peak_cost_function WHERE environment_id = ${basic_rbc_environment_id}\n) b ON b.timestep = s.timestep\nLEFT JOIN (\nSELECT timestep, value FROM  annual_peak_cost_function WHERE environment_id = ${optimized_rbc_environment_id}\n) o ON o.timestep = s.timestep\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\n(s.timestep + ${timezone_offset})*3600 AS timestamp,\ns.value/b.value AS basic,\ns.value/o.value AS optimized\nFROM annual_peak_cost_function s\nLEFT JOIN environment e ON e.id = s.environment_id\nLEFT JOIN (\nSELECT timestep, value FROM  annual_peak_cost_function WHERE environment_id = ${basic_rbc_environment_id}\n) b ON b.timestep = s.timestep\nLEFT JOIN (\nSELECT timestep, value FROM  annual_peak_cost_function WHERE environment_id = ${optimized_rbc_environment_id}\n) o ON o.timestep = s.timestep\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [ "timestamp" ]
    }
   ]
  },
  {
   "title": "Net Electric Consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 50 },
   "targets": [
    {
     "queryText": "SELECT\n(s.timestep + ${timezone_offset})*3600 AS timestamp,\ns.value/b.value AS basic,\ns.value/o.value AS optimized\nFROM net_electric_consumption_cost_function s\nLEFT JOIN environment e ON e.id = s.environment_id\nLEFT JOIN (\nSELECT timestep, value FROM  net_electric_consumption_cost_function WHERE environment_id = ${basic_rbc_environment_id}\n) b ON b.timestep = s.timestep\nLEFT JOIN (\nSELECT timestep, value FROM  net_electric_consumption_cost_function WHERE environment_id = ${optimized_rbc_environment_id}\n) o ON o.timestep = s.timestep\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\n(s.timestep + ${timezone_offset})*3600 AS timestamp,\ns.value/b.value AS basic,\ns.value/o.value AS optimized\nFROM net_electric_consumption_cost_function s\nLEFT JOIN environment e ON e.id = s.environment_id\nLEFT JOIN (\nSELECT timestep, value FROM  net_electric_consumption_cost_function WHERE environment_id = ${basic_rbc_environment_id}\n) b ON b.timestep = s.timestep\nLEFT JOIN (\nSELECT timestep, value FROM  net_electric_consumption_cost_function WHERE environment_id = ${optimized_rbc_environment_id}\n) o ON o.timestep = s.timestep\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [ "timestamp" ]
    }
   ]
  },
  {
   "title": "Electricity Consumption & Generation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short", "label": "kWh" }
   ],
   "targets": [
    {
     "queryText": "SELECT\n    (t.timestep + ${timezone_offset})*3600 AS timestamp,\n    s.electric_consumption_cooling AS cooling,\n    s.electric_consumption_dhw AS dhw,\n    s.electric_consumption_appliances AS appliances,\n    s.electric_consumption_cooling_storage AS cooling_storage,\n    s.electric_consumption_dhw_storage AS dhw_storage,\n    s.electric_consumption_electric_storage AS electric_storage,\n    s.net_electric_consumption AS net,\n    (s.net_electric_consumption + s.electric_generation) AS net_without_generation,\n    (s.net_electric_consumption + s.electric_generation - \n        (s.electric_consumption_cooling_storage + s.electric_consumption_dhw_storage + s.electric_consumption_electric_storage)\n    ) AS net_without_generation_and_storage\nFROM environment_timeseries s\nLEFT JOIN timestep t ON t.id = s.timestep_id\nLEFT JOIN environment e ON e.id = s.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "rawQueryText": "SELECT\n    (t.timestep + ${timezone_offset})*3600 AS timestamp,\n    s.electric_consumption_cooling AS cooling,\n    s.electric_consumption_dhw AS dhw,\n    s.electric_consumption_appliances AS appliances,\n    s.electric_consumption_cooling_storage AS cooling_storage,\n    s.electric_consumption_dhw_storage AS dhw_storage,\n    s.electric_consumption_electric_storage AS electric_storage,\n    s.net_electric_consumption AS net,\n    (s.net_electric_consumption + s.electric_generation) AS net_without_generation,\n    (s.net_electric_consumption + s.electric_generation - \n        (s.electric_consumption_cooling_storage + s.electric_consumption_dhw_storage + s.electric_consumption_electric_storage)\n    ) AS net_without_generation_and_storage\nFROM environment_timeseries s\nLEFT JOIN timestep t ON t.id = s.timestep_id\nLEFT JOIN environment e ON e.id = s.environment_id\nWHERE e.simulation_id = ${simulation_id}",
     "timeColumns": [ "timestamp" ]
    }
   ]
  }
 ]
}